name: repo-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}  # allow manual trigger

permissions: read-all

jobs:
  use-org-reusable:
    uses: buildiverse/.github/.github/workflows/org-hello.yml@main
    with:
      greet: "hello from ${{ github.repository }}"
      environment: "demo"
    secrets: inherit
