name: repo-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}  # allow manual trigger

permissions: read-all

jobs:
  use-org-reusable:
    uses: buildiverse/.github/.github/workflows/hello.yml@main
    secrets: inherit
